KOCSC decides what websites should be blocked
sokcuri/SaveTheInternetKR pull request #2
Opened 2019-02-17 11:37 UTC by saschanaz

This change also reflects the fact that the censorship is not new and has been there.

2019-02-17 15:28 UTC, sokcuri reviewed
SaveTheInternetKR 사이트가 생겼을때 대두되던 이슈는 "저작권법 위반 사이트"를 SNI을 들여보기까지 해서 차단을 했어야 했냐..인데 현재는 배경이 바뀌었으므로 같이 바꿔주는게 좋을것 같습니다

2019-02-17 15:29 UTC, sokcuri requested changes
수정하신 문구는 좋네요. 감사합니다.

2019-02-18 00:33 UTC, saschanaz commented
>SaveTheInternetKR 사이트가 생겼을때 대두되던 이슈는 "저작권법 위반 사이트"를 SNI을 들여보기까지 해서 차단을 했어야 했냐..인데

방통위법이나 정통망법에는 저작권법 위반에 대한 통신 제재 내용은 존재하지 않습니다. 밤토끼 차단 당시 사실 음란물 관련으로 차단된 것은 아니냐는 이야기도 있었는데, 추측성 내용을 넣기는 좀 꺼려지네요. 어떤 내용을 추가하면 좋을까요?

2019-02-18 11:57 UTC, sokcuri commented
저작권 침해에 대한 차단 법적 근거는 저작권법 104조입니다
* http://www.law.go.kr/lsLinkProc.do?lsClsCd=L&lsNm=%EC%A0%80%EC%9E%91%EA%B6%8C%EB%B2%95&lsId=prec20080805&joNo=010400&efYd=20080805&mode=11&lnkJoNo=undefined

밤토끼도 저작권법 위반으로 차단된게 맞긴 합니다만, 법적 근거가 없어서 방심위로 이관되었습니다.
* [제2의 밤토끼 잡는다…불법사이트 차단 절차 간소화 추진](http://www.edaily.co.kr/news/read?newsId=02725686619273208&mediaCodeNo=257)
* [문체부, 해외사이트 불법유통 콘텐츠 심의 손 뗀다](http://www.zdnet.co.kr/view/?no=20190104185140)


그밖의 참고자료
* [그루브샤크 차단과 우회](https://medium.com/medium-users-group-korea/%EA%B7%B8%EB%A3%A8%EB%B8%8C%EC%83%A4%ED%81%AC-%EC%B0%A8%EB%8B%A8%EA%B3%BC-%EC%9A%B0%ED%9A%8C-603093a37b32)

2019-02-18 12:04 UTC, saschanaz commented
>저작권 침해에 대한 차단 법적 근거는 저작권법 104조입니다

저작권법 104조가 말하는 '온라인서비스제공자'는 동법 제2조30에 따라 통신망을 이용하는 서비스로 정의되어 있는데 그게 통신망 그 자체는 아닌 것으로 보입니다.

2019-02-18 12:17 UTC, saschanaz commented
@sokcuri 자료는 좋은데 그래서 제가 어떤 변화를 주어야 PR 머지가 되는지 잘 모르겠습니다. 어떤 내용 추가를 원하시는지 조금 더 구체적으로 알 수 있을까요? 이 PR의 주제는 '어떤 점이 바뀌느냐' 섹션에 대한 내용 변경인데 저작권법 이야기는 기존 법령에 있으므로 딱히 바뀌는 건 아닌 것 같습니다.

2019-02-18 14:26 UTC, sokcuri commented
PR은 받아들이고 내용에 대해서 조금 더 고민해 보겠습니다. 감사합니다.

2019-02-18 14:26 UTC, merged